name: Discord Bot API Tester

on:
  schedule:
    # - cron: "0 * * * *" # Runs every hour
    - cron: "*/2 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  run-discord-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Specify your preferred Python version

      # Install Playwright and dependencies
      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py playwright requests
          pip install -r requirements.txt

      # Run the Discord bot
      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python api_bot.py
