name: Discord Bot API Tester

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發
  schedule:
    - cron: "0 * * * *" # 每小時運行一次（建議)
  workflow_dispatch: # 允許手動觸發

jobs:
  run-discord-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 簽出程式碼
        uses: actions/checkout@v4

      - name: 設定 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安裝系統依賴
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            ca-certificates \
            fonts-liberation \
            libappindicator3-1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libnspr4 \
            libnss3 \
            libxss1 \
            xdg-utils \
            libcairo2 \
            libdrm2 \
            libegl1 \
            libgbm1 \
            libglib2.0-0 \
            libpango-1.0-0 \
            libx11-6 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libwayland-client0

      - name: 安裝 Python 依賴
        run: |
          python -m pip install --upgrade pip
          pip install discord.py playwright requests
          python -m playwright install

      - name: 執行機器人
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python api_bot.py
