name: Discord Bot API Tester

on:
  schedule:
    - cron: "*/2 * * * *" # 每 2 分鐘運行一次
  workflow_dispatch: # 允許手動觸發

jobs:
  run-discord-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # 指定你想使用的 Python 版本

      # 安裝 Playwright 和依賴
      - name: Install Playwright dependencies
        run: |
          python -m pip install playwright
          playwright install --with-deps

      # 安裝 Python 依賴
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 運行 Discord bot
      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python api_bot.py
